"""
Database service for the Election Assistant.
Provides an abstraction layer over Firestore with a local MockDB fallback.
Supports chat history retrieval and message persistence.
"""
import os
import time
import logging
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)

try:
    import firebase_admin
    from firebase_admin import credentials, firestore
    _FIREBASE_AVAILABLE = True
except ImportError:
    firebase_admin = None
    _FIREBASE_AVAILABLE = False

# Global DB reference (Firestore client or MockDB instance)
db: Optional[Any] = None


def init_db() -> None:
    """
    Initializes the database connection.

    Attempts to connect to Google Cloud Firestore using credentials
    specified in the FIREBASE_CREDENTIALS environment variable.
    Falls back to MockDB (in-memory store) if credentials are missing
    or Firebase Admin SDK is not installed.
    """
    global db
    if db is not None:
        return  # Already initialized

    if _FIREBASE_AVAILABLE and not firebase_admin._apps:
        cred_path = os.environ.get("FIREBASE_CREDENTIALS")
        if cred_path and os.path.exists(cred_path):
            try:
                cred = credentials.Certificate(cred_path)
                firebase_admin.initialize_app(cred)
                db = firestore.client()
                logger.info("Firestore initialized successfully.")
                return
            except Exception as exc:
                logger.warning("Firestore initialization failed: %s. Falling back to MockDB.", exc)
        else:
            logger.info("No Firebase credentials found. Running with local MockDB.")
    elif not _FIREBASE_AVAILABLE:
        logger.info("Firebase Admin SDK not installed. Running with local MockDB.")

    db = MockDB()


class MockDB:
    """
    In-memory database mock that mirrors the Firestore session/message structure.
    Used for local development and when Firestore is unavailable.

    Attributes:
        sessions: A dict mapping session_id → list of message dicts.
    """

    def __init__(self) -> None:
        self.sessions: Dict[str, List[Dict[str, Any]]] = {}

    def save_message(self, session_id: str, message_data: Dict[str, Any]) -> None:
        """
        Persist a single message dict under the given session_id.

        Args:
            session_id: Unique identifier for the conversation session.
            message_data: Dict containing user_message, assistant_message, and timestamp.
        """
        if session_id not in self.sessions:
            self.sessions[session_id] = []
        self.sessions[session_id].append(message_data)

    def get_messages(self, session_id: str, limit: int = 5) -> List[Dict[str, Any]]:
        """
        Retrieve the most recent messages for a session.

        Args:
            session_id: Session to retrieve messages for.
            limit: Maximum number of recent messages to return.

        Returns:
            A list of message dicts, ordered chronologically (oldest first).
        """
        return self.sessions.get(session_id, [])[-limit:]


def save_chat_message(session_id: str, user_message: str, assistant_message: str) -> None:
    """
    Saves a user/assistant message pair to the database.

    Automatically initializes the DB if not already done.

    Args:
        session_id: Conversation session identifier.
        user_message: The message sent by the user.
        assistant_message: The response generated by the assistant.
    """
    global db
    if db is None:
        init_db()

    message_data: Dict[str, Any] = {
        "user_message": user_message,
        "assistant_message": assistant_message,
        "timestamp": time.time()
    }

    if isinstance(db, MockDB):
        db.save_message(session_id, message_data)
    else:
        try:
            doc_ref = db.collection("sessions").document(session_id)
            doc_ref.set({"lastActive": time.time()}, merge=True)
            doc_ref.collection("messages").add(message_data)
        except Exception as exc:
            logger.error("Error writing to Firestore: %s", exc)


def get_chat_history(session_id: str, limit: int = 5) -> List[Dict[str, Any]]:
    """
    Retrieves the most recent conversation history for a session.

    Args:
        session_id: The unique session identifier.
        limit: Maximum number of recent messages to return. Defaults to 5.

    Returns:
        A list of message dicts ordered chronologically (oldest first).
        Returns an empty list if the session does not exist or an error occurs.
    """
    global db
    if db is None:
        init_db()

    if isinstance(db, MockDB):
        return db.get_messages(session_id, limit)

    try:
        messages_ref = (
            db.collection("sessions")
            .document(session_id)
            .collection("messages")
        )
        query = messages_ref.order_by(
            "timestamp", direction=firestore.Query.DESCENDING
        ).limit(limit)
        results = query.stream()

        history = [doc.to_dict() for doc in results]
        return history[::-1]  # Reverse to get chronological order

    except Exception as exc:
        logger.error("Error reading from Firestore: %s", exc)
        return []
